import {browser} from '../browserApi';
import {
  CREATE_LOBBY,
  SYNC_LOBBY,
  UNSYNC_LOBBY,
  VIDEO_CONTROL,
} from '../messageTypes';

console.info('Team Watch injected..');

(function() {

  browser.runtime.onMessage.addListener(onCreateLobby);
  browser.runtime.onMessage.addListener(onSync);

  let videoIdentity;
  let lobbyId;
  let port;
  let video;
  let isProgramPlayAction = false;
  let isProgramPauseAction = false;
  let isProgramSeekAction = false;

  function onCreateLobby({type, payload}, sender, isCreatedCallback) {
    if (type !== CREATE_LOBBY) return;

    videoIdentity = createVideoIdentity();

    if (!videoIdentity) {
      isCreatedCallback(false);
    }
    isCreatedCallback(true);

    browser.runtime.onMessage.removeListener(onCreateLobby);
    browser.runtime.onMessage.removeListener(onSync);

    video = getVideo();

    port = browser.runtime.connect();

    //TODO: get lobbyId generated by firebase
    port.onMessage.addListener(onCreatedLobbyIdGenerated);

    const videoState = {
      isPlaying: !video.paused,
      time: video.currentTime,
    };
    port.postMessage({
      type: CREATE_LOBBY,
      payload: {
        name: payload.name,
        videoIdentity,
        videoState,
      },
    });
  }

  function onCreatedLobbyIdGenerated({type, payload}) {
    if (type !== CREATE_LOBBY) return;

    port.onMessage.removeListener(onCreatedLobbyIdGenerated);

    lobbyId = payload.lobbyId;

    port.onMessage.addListener(onVideoControl);

    setVideoEventCallbacks();

    browser.runtime.onMessage.addListener(onUnsync);
  }

  function onSync({type, payload}, sender, isSyncedCallback) {
    if (type !== SYNC_LOBBY) return;

    const isVideoIdentityMatched = matchVideoIdentity(payload.videoIdentity);
    if (!isVideoIdentityMatched) {
      isSyncedCallback(false);
      return;
    }
    isSyncedCallback(true);

    browser.runtime.onMessage.removeListener(onCreateLobby);
    browser.runtime.onMessage.removeListener(onSync);

    videoIdentity = payload.videoIdentity;
    lobbyId = payload.lobbyId;

    video = getVideo();

    port = browser.runtime.connect();
    port.onMessage.addListener(onVideoControl);

    port.postMessage({
      type: SYNC_LOBBY,
      payload: {
        lobbyId: payload.lobbyId,
      },
    });

    setVideoEventCallbacks();

    browser.runtime.onMessage.addListener(onUnsync);
  }

  function setVideoEventCallbacks() {
    video.onplay = () => {
      if (isProgramPlayAction) {
        console.log('Play is triggered by program.');
        isProgramPlayAction = false;
        return;
      }

      const payload = {
        isPlaying: true,
      };
      console.
          log('Play is triggered by player and send to eventPage:', payload);
      port.postMessage({
        type: VIDEO_CONTROL,
        payload,
      });
    };

    video.onpause = () => {
      if (isProgramPauseAction) {
        console.log('Pause is triggered by program.');
        isProgramPauseAction = false;
        return;
      }

      const payload = {
        isPlaying: false,
        time: video.currentTime,
      };
      console.
          log('Pause is triggered by player and send to eventPage:', payload);
      port.postMessage({type: VIDEO_CONTROL, payload});
    };

    video.onseeked = () => {
      if (isProgramSeekAction) {
        isProgramSeekAction = false;
      }

      const payload = {
        isPlaying: false,
        time: video.currentTime,
      };
      console.log('Seek triggered and send to eventPage:', payload);
      port.postMessage({type: VIDEO_CONTROL, payload});

      if (!video.paused) {
        console.log('Trigger pause because video is not paused.');
        isProgramPauseAction = true;
        video.pause();
      }
    };
  }

  function createVideoIdentity() {
    const url = new URL(document.location.href);
    const hostname = url.hostname;
    if (hostname === 'www.youtube.com') {
      const v = url.searchParams.get('v');
      if (v) return {hostname, v};
    }
    return null;
  }

  function matchVideoIdentity(videoIdentity) {
    const url = new URL(document.location.href);
    if (url.hostname === videoIdentity.hostname) {
      return url.searchParams.get('v') === videoIdentity.v;
    }
    return false;
  }

  function getVideo() {
    return document.getElementsByClassName('video-stream html5-main-video')[0];
  }

  function onVideoControl({type, payload}) {
    if (type !== VIDEO_CONTROL) return;

    console.log('From eventPage:', payload);

    if (payload.hasOwnProperty('isPlaying')) {
      if (payload.isPlaying) {
        if (video.paused) {
          isProgramPlayAction = true;
          video.play();
        }
      } else {
        if (!video.paused) {
          isProgramPauseAction = true;
          video.pause();
        }
      }
    }
    if (payload.hasOwnProperty('time')) {
      isProgramSeekAction = true;
      video.currentTime = payload.time;
    }
  }

  function onUnsync({type, payload}) {
    if (type !== UNSYNC_LOBBY || lobbyId !== payload.lobbyId) return;

    browser.runtime.onMessage.removeListener(onUnsync);

    port.onMessage.removeListener(onVideoControl);

    if (video) {
      video.onplay = null;
      video.onpause = null;
      video.onseeked = null;
      video = null;
    }

    port.disconnect();
    port = null;

    videoIdentity = null;
    lobbyId = null;
    isProgramPlayAction = false;
    isProgramPauseAction = false;
    isProgramSeekAction = false;

    browser.runtime.onMessage.addListener(onSync);
  }

})();
