export const CONNECT_TO_LOBBY = 'CONNECT_TO_LOBBY';
export const DISCONNECT_FROM_LOBBY = 'DISCONNECT_FROM_LOBBY';
export const LINK_WITH_LOBBY = 'LINK_WITH_LOBBY';
export const BREAK_LINK_WITH_LOBBY = 'BREAK_LINK_WITH_LOBBY';
export const VIDEO_CONTROL = 'VIDEO_CONTROL';
