export const CREATE_LOBBY = 'CREATE_LOBBY';
export const CONNECT_TO_LOBBY = 'CONNECT_TO_LOBBY';
export const DISCONNECT_FROM_LOBBY = 'DISCONNECT_FROM_LOBBY';
export const SYNC_WITH_LOBBY = 'SYNC_WITH_LOBBY';
export const UNSYNC_WITH_LOBBY = 'UNSYNC_WITH_LOBBY';
export const VIDEO_CONTROL = 'VIDEO_CONTROL';
export const NEW_VIDEO_TO_LOBBY = 'NEW_VIDEO_TO_LOBBY';