export const CREATE_LOBBY = 'CREATE_LOBBY';
export const NEW_VIDEO_TO_LOBBY = 'NEW_VIDEO_TO_LOBBY';
export const CONNECT_LOBBY = 'CONNECT_LOBBY';
export const DISCONNECT_LOBBY = 'DISCONNECT_LOBBY';
export const SYNC_LOBBY = 'SYNC_LOBBY';
export const UNSYNC_LOBBY = 'UNSYNC_LOBBY';
export const VIDEO_CONTROL = 'VIDEO_CONTROL';
export const REMOVE_LOBBY = 'REMOVE_LOBBY';
